# Self-Hosted Github Action Runners on AWS via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml
runners:
  - name: "aws-runner"
    # Cloud Provider: AWS
    cloud: "aws"
    # V100 16GB $3.06/hr
    instance_type: "p3.2xlarge"
    # ami: Deep Learning Base OSS Nvidia Driver GPU AMI (Ubuntu 20.04) 20240101
    machine_image: "ami-0a8dada81f29ad054"
    preemptible: false
    # Add this label in the "runs-on" param in .github/workflows/<workflow-name>.yml
    # So that this runner is created for running the workflow
    labels:
      - "cirun-aws-gpu-runner"
