version: 0.2

phases:
  pre_build:
    commands:
      - echo Starting the build process...
      - echo Current working directory:
      - pwd
      - ls -la
      - git fetch --all
      - git checkout feat/deploy
      - echo "Commit ID:"
      - git rev-parse HEAD
      - git reset --hard origin/feat/deploy
      - echo "Post-checkout file listing:"
      - ls -la
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 726461418004.dkr.ecr.us-east-1.amazonaws.com/guiai-app:latest .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 726461418004.dkr.ecr.us-east-1.amazonaws.com/guiai-app:latest
      - echo Build completed on `date`