# docker-build.yml.j2
name: Docker Build with AWS CodeBuild

on:
  push:
    branches:
      - feat/deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
          aws-region: us-east-1

      - name: Start AWS CodeBuild
        run: |
          aws codebuild start-build --project-name guiai